#!/usr/bin/env bash
echo ""
echo "Deploy vimrc settings......"

rm -rf $HOME/.vim
rm -rf $HOME/.vimrc
rm -rf $HOME/.gvimrc

current_path="${PWD}"

rm -rf $current_path/bundle
git clone https://github.com/gmarik/vundle.git $current_path/bundle/vundle 

ln -s $current_path $HOME/.vim
ln -s $current_path/vimrc $HOME/.vimrc


vim +BundleInstall +qall


echo "Deploy done."
